name: Pubspec Version Check
author: Nico Franke
description: An action that allows you to check whether your pubspec version has been updated

inputs:
  file-name:
    description: A custom path to the pubspec.yaml file
    required: false
  token:
    description: A GitHub token to use when running on private repos
    required: false

outputs:
  changed:
    description: Whether the version has changed in the examined commits
  type:
    description: The type of version change, if detectable (e.g. 'patch')
  version:
    description: The detected version number
    
runs:
  using: 'node12'
  main: 'dist/main.js'
