name: Build & lint
on:
  push:
    branches-ignore:
      - dist

jobs:
  build:
    name: Build compiled JS version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install dependencies
        run: npm install

      - name: Compile TypeScript into compressed JavaScript
        run: npm run build

      - name: Commit changes
        uses: EndBug/add-and-commit@v2
        with:
          force: true
          message: "[auto] Update compiled version"
          path: lib
          pattern: "*.js"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  lint:
    name: Lint source files
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install dependencies
        run: npm install

      - name: Lint source code with ESLint
        run: npm run lintfix
      - name: Commit changes
        uses: EndBug/add-and-commit@v2
        with:
          message: "[auto] Lint source code"
          path: src
          pattern: "*.*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
